version: '2'

services:
  consul:
    image: consul:0.8.3
    ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    links:              # Link Consul to demo microservices
    - gin-web-01
    - gin-web-02
    networks:
    - sky-net
  gin-web-01:           # Register these services to Consul
    image: aymanpatel/gin-web:1.0.1
    environment: 
    - PORT=9080
    ports:
    - "9080:9080"
    networks:
    - sky-net
  gin-web-02:
    image: aymanpatel/gin-web:1.0.1
    environment: 
    - PORT=9090
    ports:
    - "9090:9090"
    networks:
    - sky-net

networks:
  sky-net:
    driver: bridge


